alias slackware='screen VBoxHeadless -s slacker\ rises\ again'
alias slackroot='ssh root@192.168.1.12'
alias slackuser='ssh user@192.168.1.12'
alias ada='ssh davmax04@ada.evergreen.edu'
alias apt='sudo apt-get install'
alias ..='cd ..'
alias ...='cd ../..'
